[microceph]
srv-microceph-01 ansible_host=10.205.166.219 ansible_user=root ansible_python_interpreter=/usr/bin/python3
srv-microceph-02 ansible_host=10.205.166.220 ansible_user=root ansible_python_interpreter=/usr/bin/python3
srv-microceph-03 ansible_host=10.205.166.221 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[microceph_bootstrap]
srv-microceph-01 ansible_host=10.205.166.219 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[microceph_workers]
srv-microceph-02 ansible_host=10.205.166.220 ansible_user=root ansible_python_interpreter=/usr/bin/python3
srv-microceph-03 ansible_host=10.205.166.221 ansible_user=root ansible_python_interpreter=/usr/bin/python3

[local]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3
